# Координаты текста
xyz: 0 100 0



# Текст таймера
text: |-
  §l§7До §r§cН§fо§cв§fо§cг§fо§r§l года
  
  §7> [§eДни > §l§f{days}
  §7> [§eЧасы > §l§f{hours}
  §7> [§eМинуты > §l§f{minutes}
  §7> [§eСекунды > §l§f{seconds}§r

# Текст к новому году
holiday: |-
  §f§l==============================
  §c>§f>§c> §r§lНОВЫЙ ГОД :)§r§c <§f<§c
  §f§l==============================